# Generated by Django 5.1.2 on 2024-11-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(db_column='NOME')),
                ('sobrenome', models.TextField(db_column='SOBRENOME')),
                ('genero', models.TextField(db_column='GENERO')),
                ('dtNasc', models.DateField(db_column='DTNASC')),
                ('idade', models.PositiveIntegerField(db_column='IDADE')),
                ('distancia', models.TextField(db_column='DISTANCIA')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'corrida_pessoa',
                'ordering': ['user_id'],
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='corrida_pessoa',
        ),
    ]
